TRUTH = (
    "Acara tv apa yang paling kamu benci? Berikan alasannya!",
    "Apa hal paling buruk (gosip) yang pernah kamu bilang tentang temenmu?",
    "Apa hal paling memalukan dari dirimu?",
    "Apa hal paling memalukan dari temanmu?",
    "Apa hal pertama yang kamu lihat saat kamu melihat orang lain (lawan jenis)??",
    "Apa hal pertama yang terlintas di pikiranmu saat kamu melihat cermin?",
    "Apa hal terbodoh yang pernah kamu lakukan?",
    "Apa ketakutan terbesar kamu?",
    "Apa mimpi terburuk yang pernah kamu alami?",
    "Apa mimpi terkonyol yang sampai sekarang kamu kamu ingat?",
    "Apa pekerjaan paling konyol yang pernah kamu bayangin kamu akan jadi?",
    "Apa sifat terburukmu menurut kamu?",
    "Apa sifat yang ingin kamu rubah dari dirimu?",
    "Apa yang kamu fikirkan sebelum kamu tidur?",
    "Siapa orang terakhir yang kamu stalking di media sosial??",
    "Apa love language kamu?",
    "Apa quotes favoritmu?",
    "Lagu apa yang paling sering kamu putar pas lagi down atau overthinking?",
    "Hal apa yang kamu harapkan bisa kamu ubah dari diri sendiri?",
    "Siapa nih crush rahasia kamu?",
    "Pernah selingkuh atau diselingkuhin? jujur!",
    "Sebutkan bagian tubuh (crush) yang kamu suka?",
    "Apa hidden talent nu?",
    "Pernah suka sama sahabat atau temen sendiri?",
    "Yang menurutmu orang paling baik di gc ini? coba tag!",
    "Yang menurutmu orang paling ngeselin di gc ini? tag orangnya, maki maki kalo perlu hehe!",
    "Kalo kamu off telegram, siapa (orang di gc ini) yang bakal kamu kangenin?",
    "Kalo orang terdekatmu di gc ini tiba tiba off, kamu mau bilang apa sebelum dia hilang kabar?",
    "Pelajaran hidup ter the best yang kamu ambil apa? coba kasih tau kita",
)

DARE = (
    "Chat orang random, bilang “aku suka kamu”"
    "Chat mama kalian, bilang “ma mau nikah”",
    "Spill ssan terakhir chat sama mantan!",
    "Bilang kangen ke mantan kalian!",
    "Chat “hai” ke crush kalian!",
    "Jawab “iya” kalo crush kalian ada di gc ini!",
    "Spill playlist spotify atau youtube kalian.",
    "Spill ssan list pc kalian.",
    "Spill nama mantan yang kalian benci atau mantan yang paling menyakitkan.",
    "tyfhing jmethie slmah permainan selesai 😎🤙",
    "ss game di hp mu",
    "belanjain (grab/gofood) buat salah satu pemain disini, terserah siapa. budget dibawah 25k",
    "Bilang “AKU SUKA SAMA KAMU” ke crush",
    "Chat ke mantan bilang “hai aku kangen”",
    "minta mantan/crush/pacar/sahabat kamu buat nyanyiin 1 part lagu, good luck!",
    "Menyanyikan lagu HAI TAYO di random people",
    "Sebutin jumlah mantan dan inisialnya!",
    "Vn ke pacar/crush/mantan bilang “hai, call yuk”, lalu ss ke sini!",
    "Ganti ava capelan sama pemain (terserah siapa) sampai permainan selesai",
    "Spill emot ter-fav kalian.",
    "Spill pap/stiker muka kalian yang menurut kalian cantik atau ganteng",
    "Sebutkan nama guru killer SMK/SMA kalian.",
    "Tag dan bilang “berantem yuk?” ke orang yang menurutkan kalian ngeselin",
    "Ss dman ig kalian",
    "Spill filter ig ter-fav kalian",
    "Aplikasi fav kalian selain tele/tiktok.",
    "Aplikasi yang bermanfaat buat kalian.",
    "Spill baju yang sering kalian pake",
    "Ganti nama tele “(nama kalian) Manager PT. Mencari Cinta Sejati”.",
    "Sebut nama orang yang pernah bikin kamu nangis",
    "Spill chat yang pernah bikin kalian galau atau overthinking!",
    "Calls sama orang (terserah siapa) selama 1 menit, lalu ss kesini!",
    "Ss chat yang bisa bikin kalian baper!",
    "Tag random people lalu katain (terserah ngatain apa aja).",
    "Minta ke pacar/crush/mantan/temen buat nyanyiin kalian, goodluck!",
)
